# app in sinatra with a mongodb

# app
version: "3.1"

services:
  web:
    tty: true
    stdin_open: true
    build:
      context: .
      args:
        - environment=development
      dockerfile: ./devops/docker/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - mongo

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mongo
    volumes:
      - ./data:/data/db

networks:
  mongo:
